apiVersion: devops.alauda.io/v1alpha1
kind: PipelineTaskTemplate
metadata:
  name: fusionStageDeployServiceWithCustomImage
  annotations:
    alauda.io/displayName.zh-CN: 更新应用
    alauda.io/displayName.en: DeployApplication
    alauda.io/description.zh-CN: 更新应用，使用 fusionstage 镜像
    alauda.io/description.en: DeployApplication
    alauda.io/readme.zh-CN: 更新应用
    alauda.io/readme.en: DeployApplication
    alauda.io/version: "0.0.1"
    alauda.io/style.icon: 
  labels:
    catgory: CD
    phase: inclubator
spec:
  engine: gotpl
  body: |+
    script{
      String token_endpoint = "${TOKEN_ENDPOINT}"
      String deploy_endpoint = "${DEPLOY_ENDPOINT}"

      try{
        fusionStage.deploy(token_endpoint,deploy_endpoint,'{{.projectId}}','{{.applicationName}}', '{{.containerName}}', '{{.domainName}}','{{.username}}','{{.password}}', '{{.imageRepository}}:{{.imageTag}}')
      }catch(Exception err){
        {{if .EnableJira -}}
        def testIssue = [fields: [
           project: [key: '{{.projectKey}}'],
           summary: '{{.summary}}',
           description: '{{.description}}',
           issuetype: [id: '10004']]]

        response = jiraNewIssue issue: testIssue,site: env.JIRA_SITE
        echo response.data.toString()
        {{- end}}
         throw err
        }

    }
  arguments:
    - name: domainName
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: 租户名称
          en: Domain ID
        description:
          zh-CN: 租户名称
          en: Domain ID
      required: true
    - name: username
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: 用户名
          en: Username
        description:
          zh-CN: 用户名
          en: Username
      required: true
    - name: password
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: 密码
          en: Password
        description:
          zh-CN: 密码
          en: Password
      required: true
    - name: projectId
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: 项目 ID
          en: Project ID
        description:
          zh-CN: 项目 ID
          en: Project ID
      required: true
    - name: applicationName
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: 应用名称
          en: Application Name
        description:
          zh-CN: 应用名称
          en: Application Name
      required: true
      validation:
        pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
    - name: containerName
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: 容器名称
          en: Container Name
        description:
          zh-CN: 容器名称
          en: Container Name
      required: true
      validation:
        pattern: ^[a-zA-Z]([-a-zA-Z0-9]*[a-zA-Z0-9])?$
    - name: "imageRepository"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "镜像仓库"
          en: "Dockerfile"
        description:
          zh-CN: "格式：host:port/imagename"
          en: "host:port/image"
      required: true
      default: ''
    - name: "imageTag"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "镜像 tag"
          en: "imageTag"
        description:
          zh-CN: "镜像 tag"
          en: "image tag"
      required: true
      default: 'latest'
    - name: "command"
      schema:
        type: string
      required: false
      display:
        type: string
        advanced: true
        name:
          zh-CN: "启动命令"
          en: "command"
        description:
          zh-CN: "即 command，相当于 Dockerfile 中的 ENTRYPOINT 命令。如果没有指定启动命令，将使用容器镜像中的 ENTRYPOINT"
          en: "command"
    - name: "args"
      schema:
        type: string
      required: false
      display:
        type: string
        advanced: true
        name:
          zh-CN: "参数"
          en: "args"
        description:
          zh-CN: "即 args，相当于 Dockerfile 中的 CMD，负责提供启动命令的命令参数。如果没有指定参数，将使用容器镜像中的 CMD"
          en: "args"
    - name: timeout
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "超时时间（秒）"
          en: "Timeout (s)"
        description:
          zh-CN: "当前任务的执行时间若超过超时时间，则会中止任务，流水线变为失败状态"
          en: "timeout"
      required: true
    - name: "EnableJira"
      schema:
        type: boolean
      required: false
      display:
        type: boolean
        name:
          zh-CN: "创建JIRA Issue"
          en: "Create JIRA Issue"
        description:
          zh-CN: "创建JIRA Issue"
          en: "Create JIRA Issue"
    - name: "projectKey"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "项目关键字"
          en: "projectKey"
        description:
          zh-CN: "项目关键字"
          en: ""
      required: true
      default: ''
    - name: "description"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "描述"
          en: "description"
        description:
          zh-CN: "描述"
          en: ""
      required: true
      default: ''
    - name: "summary"
      schema:
        type: string
      display:
        type: string
        name:
          zh-CN: "标题"
          en: "summary"
        description:
          zh-CN: "标题"
          en: ""
      required: true
      default: ''
